
services:
  backend:
    build: .
    environment:
      - PYTHONPATH=/app/src
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    command: ["python", "src/presentation/main.py"]

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5440:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollamadata:/root/.ollama

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27027:27017"
    volumes:
      - ./mongo:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"    

volumes:
  postgresdata:
  ollamadata:
    